version: '3.8'

services:
  task-tracker-postgres:
    image: postgres:latest
    volumes:
      - ./pg_data:/var/lib/postgresql
    networks:
      - default
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  task-tracker-backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - task-tracker-postgres